import React from 'react';
import { Cpu, Zap, Layers, Sparkles, CheckCircle2, ShieldAlert } from 'lucide-react';

export interface StackOption {
  id: string;
  name: string;
  desc: string;
  descTh: string;
  features: string[];
  featuresTh: string[];
  performance: string;
  performanceTh: string;
  database: string;
  cache: string;
  bestFor: string;
  bestForTh: string;
}

const STACKS: StackOption[] = [
  {
    id: 'go-gin',
    name: 'Go (Gin) + PostgreSQL + Redis',
    desc: 'Ultra-low latency compiled backend designed for massive throughput and high concurrency.',
    descTh: 'ภาษา Go แบบคอมไพล์ที่มี Latency ต่ำพิเศษ ออกแบบมาเพื่อรองรับทราฟฟิกระดับล้านและจองสิทธิ์พร้อมกันแบบเรียลไทม์',
    features: ['Goroutines lightweight concurrency', 'Minimal memory footprints', 'High throughput database pool'],
    featuresTh: ['Goroutines จัดการ Concurrency ประหยัดแรม', 'ใช้ทรัพยากร CPU/RAM ต่ำมาก', 'การเชื่อมต่อ DB Pool ประสิทธิภาพสูง'],
    performance: '60,000+ RPS / Pod',
    performanceTh: '60,000+ RPS / Pod (เร็วสุดยอด)',
    database: 'PostgreSQL Primary-Replica',
    cache: 'Redis Distributed Cluster (Seat-locks)',
    bestFor: 'Ingestion spikes, ticket sales, distributed locks',
    bestForTh: 'ระบบกดบัตร, ระบบจองที่นั่ง, ตู้ธุรกรรมขนาดใหญ่'
  },
  {
    id: 'node-express',
    name: 'Node.js (Express) + MongoDB + Redis',
    desc: 'Perfect asynchronous framework for real-time web applications, chat nodes, and JSON stream APIs.',
    descTh: 'เฟรมเวิร์ก Asynchronous ยอดนิยมสำหรับแชตเรียลไทม์, ข้อความคู่ขนาน, และ API ประมวลผล JSON ด่วน',
    features: ['Single-threaded event loop architecture', 'Fast document store storage', 'Native socket connection channels'],
    featuresTh: ['สถาปัตยกรรม Event Loop ยิงงานแบบ Asynchronous', 'การเก็บข้อมูลแบบ Document รวดเร็วไม่มีโครงสร้าง', 'รองรับการทำ WebSockets/WSS ดับเบิ้ลท่อด่วน'],
    performance: '25,000+ RPS / Pod',
    performanceTh: '25,000+ RPS / Pod (เร็ว/ยืดหยุ่นสูง)',
    database: 'MongoDB Document Cluster',
    cache: 'Redis Presence Cache (Online states)',
    bestFor: 'Real-time messaging, collaboration platforms, dynamic feeds',
    bestForTh: 'แชตบอร์ดเรียลไทม์, ระบบฟีดฟอรั่ม, และแอปพลิเคชันคอลแลบทีม'
  },
  {
    id: 'python-fastapi',
    name: 'Python (FastAPI) + PostgreSQL + Redis',
    desc: 'Speedy modern Python engine tuned for microservices, machine learning inferences, and AI agents.',
    descTh: 'ระบบประมวลผลด่วนในภาษา Python เหมาะสำหรับงาน Microservices เชื่อมต่อ AI, โมเดล AI และ Data Pipelines',
    features: ['Asynchronous async/await async core', 'Autogenerated OpenAPI schemas', 'Easy ML/data ecosystem bindings'],
    featuresTh: ['รองรับ Asynchronous async/await แท้', 'สร้างเอกสาร API (Swagger) ให้เองแบบอัตโนมัติ', 'เชื่อมโยงโมเดล AI/ML และวิเคราะห์คิวข้อมูลสะดวกสุด'],
    performance: '18,000+ RPS / Pod',
    performanceTh: '18,000+ RPS / Pod (วิเคราะห์แม่นยำ)',
    database: 'PostgreSQL SQL Client',
    cache: 'Redis Task Queue (Celery/Broker)',
    bestFor: 'AI pipeline triggers, generative pipelines, predictive analytics',
    bestForTh: 'ระบบหลังบ้านรันโมเดล AI, Data Analytics, และประมวลผลไฟล์ขนาดใหญ่'
  },
  {
    id: 'java-springboot',
    name: 'Java (Spring Boot) + PostgreSQL + Redis',
    desc: 'Rigid, secure enterprise standard with mature transactional ledgers and robust DB connection pools.',
    descTh: 'มาตรฐานอุตสาหกรรมระดับองค์กรที่ทนทาน ปลอดภัยสูง มีระบบตรวจสอบธุรกรรมและ HikariCP เชื่อมฐานข้อมูลแกร่ง',
    features: ['Spring JPA robust ORM mapping', 'Mature multi-threading security', 'HikariCP reliable connection management'],
    featuresTh: ['Spring JPA จัดการ ORM และธุรกรรมการเงินเข้มงวด', 'ความปลอดภัยและการกั้น Thread ปลอดภัยระดับแบงก์', 'ระบบ HikariCP คุมสายเชื่อมข้อมูลทนทานสูงสุด'],
    performance: '35,000+ RPS / Pod',
    performanceTh: '35,000+ RPS / Pod (แข็งแกร่ง/เสถียรที่สุด)',
    database: 'PostgreSQL Clustered Primary',
    cache: 'Redis Session Store',
    bestFor: 'Corporate banking ledgers, heavy transactions, ERP architectures',
    bestForTh: 'ระบบบัญชีธนาคารองค์กรใหญ่, เวิร์กโฟลว์การเงิน, ระบบ ERP ขนาดใหญ่'
  },
  {
    id: 'csharp-netcore',
    name: 'C# (.NET Core) + SQL Server + Redis',
    desc: 'High performance enterprise framework with cross-platform native speeds and Azure cloud ecosystem bindings.',
    descTh: 'เฟรมเวิร์กสถาปัตยกรรมระดับองค์กรจาก Microsoft ที่มีประสิทธิภาพสูงปรี๊ด เข้ากันได้ดีกับคลาวด์ Azure',
    features: ['Native Kestrel web engine speeds', 'Powerful Entity Framework Core ORM', 'Optimized Microsoft ecosystem APIs'],
    featuresTh: ['เอนจิ้นเว็บ Kestrel ความเร็วใกล้เคียงโค้ด C++', 'Entity Framework Core จัดการ DB ได้เร็วและสวยงาม', 'เข้ากันได้ดีกับคลาวด์ Azure และระบบ Enterprise Cloud'],
    performance: '42,000+ RPS / Pod',
    performanceTh: '42,000+ RPS / Pod (โครงสร้างแน่นหนา)',
    database: 'Microsoft SQL Server',
    cache: 'Redis Distributed Cache',
    bestFor: 'Cloud scale enterprise web apps, Microsoft architectures, Azure native apps',
    bestForTh: 'แอปคลาวด์ขนาดใหญ่ระดับองค์กร, สถาปัตยกรรม Windows/Azure Native'
  }
];

interface StackSelectorModalProps {
  isOpen: boolean;
  onClose: () => void;
  blueprint: any;
  onSelectStack: (stackId: string) => void;
  language: 'th' | 'en';
}

export const StackSelectorModal: React.FC<StackSelectorModalProps> = ({
  isOpen,
  onClose,
  blueprint,
  onSelectStack,
  language
}) => {
  if (!isOpen || !blueprint) return null;

  // Smart Recommendation Logic
  const getRecommendedStack = (title: string = '', description: string = '') => {
    const combined = `${title} ${description}`.toLowerCase();
    if (/concert|ticket|booking|ingest|queue|concurrency|spike|lock|กดบัตร|จองตั๋ว|บัตรคอนเสิร์ต/i.test(combined)) {
      return 'go-gin';
    }
    if (/chat|message|realtime|real-time|websocket|presence|แชท|ข้อความ/i.test(combined)) {
      return 'node-express';
    }
    if (/ai|agent|ml|machine learning|python|data|analytics|predictive|ปัญญาประดิษฐ์/i.test(combined)) {
      return 'python-fastapi';
    }
    if (/enterprise|ledger|banking|transaction|finance|erp|ธนาคาร|บัญชี/i.test(combined)) {
      return 'java-springboot';
    }
    return 'go-gin'; // Default high recommendations
  };

  const recommendedId = getRecommendedStack(blueprint.title, blueprint.description);

  return (
    <div className="fixed inset-0 bg-slate-950/85 backdrop-blur-md z-50 flex items-center justify-center p-4 overflow-y-auto select-none animate-fade-in-node">
      <div className="w-full max-w-4xl bg-slate-900/90 border border-white/10 rounded-3xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh] relative">
        
        {/* Glow Decor */}
        <div className="absolute top-0 left-1/4 -translate-y-1/2 w-96 h-32 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 right-1/4 translate-y-1/2 w-96 h-32 bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />

        {/* Header */}
        <div className="p-6 border-b border-white/5 flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-900 shrink-0 text-left">
          <div className="space-y-1">
            <h2 className="text-lg font-bold text-white flex items-center gap-2 tracking-wider">
              <Sparkles className="w-5 h-5 text-cyan-400 animate-pulse" />
              <span>
                {language === 'th' 
                  ? 'เลือกโครงสร้างภาษาและฐานข้อมูล (Backend Stacks Catalog)' 
                  : 'Choose Your Target Backend Stack'}
              </span>
            </h2>
            <p className="text-xs text-gray-400 leading-relaxed font-sans">
              {language === 'th'
                ? `สำหรับระบบ: "${blueprint.title || 'สถาปัตยกรรมของคุณ'}" — กรุณาเลือกสแต็กสำหรับรันวิเคราะห์จำลองการรับโหลดและสเกลคลาวด์`
                : `For system: "${blueprint.title || 'Your Design'}" — Select the active technology stack to customize the scaling metrics and server config parameters.`}
            </p>
          </div>
          
          <button 
            onClick={onClose}
            className="self-end md:self-auto py-1.5 px-4 rounded-xl border border-white/5 hover:bg-white/5 text-gray-400 hover:text-white text-xs font-semibold cursor-pointer transition-colors"
          >
            {language === 'th' ? 'ข้าม (ใช้ตัวเริ่มต้น)' : 'Skip & Default'}
          </button>
        </div>

        {/* Catalog List */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4 scrollbar-thin">
          {STACKS.map((stack) => {
            const isRecommended = stack.id === recommendedId;
            
            return (
              <div
                key={stack.id}
                onClick={() => onSelectStack(stack.id)}
                className={`group relative p-5 rounded-2xl border text-left flex flex-col md:flex-row justify-between gap-4 cursor-pointer transition-all duration-300 hover:scale-[1.005] ${
                  isRecommended
                    ? 'bg-slate-950/70 border-emerald-500/40 hover:border-emerald-500/70 shadow-lg shadow-emerald-950/20'
                    : 'bg-slate-950/30 border-white/5 hover:border-white/15 hover:bg-slate-950/50'
                }`}
              >
                {/* Neon pulsing ring indicator for recommended stack */}
                {isRecommended && (
                  <div className="absolute inset-0 rounded-2xl border border-emerald-400/20 animate-pulse pointer-events-none" />
                )}

                {/* Left Side: Name and Details */}
                <div className="space-y-3 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-sm font-bold text-white group-hover:text-cyan-400 transition-colors">
                      {stack.name}
                    </span>
                    
                    {isRecommended && (
                      <span className="flex items-center gap-1 bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-[9px] font-extrabold px-2 py-0.5 rounded-full select-none animate-bounce">
                        <CheckCircle2 className="w-2.5 h-2.5" />
                        <span>{language === 'th' ? 'แนะนำสำหรับผังระบบนี้' : 'RECOMMENDED FOR YOU'}</span>
                      </span>
                    )}
                  </div>

                  <p className="text-xs text-gray-400 leading-relaxed font-sans max-w-2xl">
                    {language === 'th' ? stack.descTh : stack.desc}
                  </p>

                  {/* Bullet features */}
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
                    {(language === 'th' ? stack.featuresTh : stack.features).map((feat, idx) => (
                      <div key={idx} className="flex items-center gap-1.5 text-[10px] text-gray-500">
                        <span className="w-1 h-1 rounded-full bg-cyan-400/60" />
                        <span className="truncate">{feat}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Right Side: Performance metrics */}
                <div className="md:w-56 bg-slate-900/60 border border-white/5 rounded-xl p-3.5 flex flex-col justify-between shrink-0 gap-3">
                  <div className="space-y-1.5 font-sans">
                    <div className="flex items-center justify-between text-[10px] border-b border-white/5 pb-1">
                      <span className="text-gray-500 flex items-center gap-1">
                        <Zap className="w-3 h-3 text-amber-400" />
                        {language === 'th' ? 'ประสิทธิภาพ:' : 'Speed Benchmark:'}
                      </span>
                      <span className="font-bold text-amber-400 font-mono">{language === 'th' ? stack.performanceTh : stack.performance}</span>
                    </div>

                    <div className="flex items-center justify-between text-[10px] border-b border-white/5 pb-1">
                      <span className="text-gray-500 flex items-center gap-1">
                        <Layers className="w-3 h-3 text-blue-400" />
                        Database:
                      </span>
                      <span className="font-semibold text-gray-300 truncate max-w-[110px]">{stack.database}</span>
                    </div>

                    <div className="flex items-center justify-between text-[10px] border-b border-white/5 pb-1">
                      <span className="text-gray-500 flex items-center gap-1">
                        <Cpu className="w-3 h-3 text-indigo-400" />
                        Cache Tier:
                      </span>
                      <span className="font-semibold text-gray-300 truncate max-w-[110px]">{stack.cache}</span>
                    </div>
                  </div>

                  <div className="text-[9px] text-gray-500 pt-0.5 border-t border-white/5 text-left leading-normal font-sans">
                    <strong className="text-cyan-400 uppercase tracking-wider block text-[8px] font-mono">Best For:</strong>
                    <span className="italic block truncate mt-0.5" title={language === 'th' ? stack.bestForTh : stack.bestFor}>
                      {language === 'th' ? stack.bestForTh : stack.bestFor}
                    </span>
                  </div>
                </div>

              </div>
            );
          })}
        </div>

        {/* Footnote */}
        <div className="p-4 border-t border-white/5 bg-slate-950 text-center text-[10px] text-gray-500 shrink-0">
          🔒 {language === 'th' 
            ? 'เมื่อเลือกแล้ว เอนจิ้นระบบ AI จะดัดแปลงระบบสเกล, งบประมาณ, และจูนนิ่ง Postgres/Nginx ให้ตรงภาษานั้นๆ ทันที!' 
            : 'Once selected, the Multi-Agent telemetry engine will instantly recalculate specifications specifically for your technology stack.'}
        </div>

      </div>
    </div>
  );
};
